package com.iwos.service;

import com.iwos.entity.Order;
import com.iwos.repository.OrderRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * Order Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles Order business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class OrderService {

    private final OrderRepository repository;

    /**
     * Get all Orders
     */
    @Transactional(readOnly = true)
    public List<Order> getAll() {
        log.info("Fetching all Orders");
        return repository.findAll();
    }

    /**
     * Get Order by ID
     */
    @Transactional(readOnly = true)
    public Optional<Order> getById(Long id) {
        log.info("Fetching Order with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create Order
     */
    public Order create(Order entity) {
        log.info("Creating new Order");
        return repository.save(entity);
    }

    /**
     * Update Order
     */
    public Order update(Long id, Order entity) {
        log.info("Updating Order with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Order
     */
    public void delete(Long id) {
        log.info("Deleting Order with ID: {}", id);
        repository.deleteById(id);
    }
}
