package com.iwos.service;

import com.iwos.entity.OrderStatusHistory;
import com.iwos.repository.OrderStatusHistoryRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * OrderStatusHistory Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles OrderStatusHistory business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class OrderStatusHistoryService {

    private final OrderStatusHistoryRepository repository;

    /**
     * Get all OrderStatusHistorys
     */
    @Transactional(readOnly = true)
    public List<OrderStatusHistory> getAll() {
        log.info("Fetching all OrderStatusHistorys");
        return repository.findAll();
    }

    /**
     * Get OrderStatusHistory by ID
     */
    @Transactional(readOnly = true)
    public Optional<OrderStatusHistory> getById(Long id) {
        log.info("Fetching OrderStatusHistory with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create OrderStatusHistory
     */
    public OrderStatusHistory create(OrderStatusHistory entity) {
        log.info("Creating new OrderStatusHistory");
        return repository.save(entity);
    }

    /**
     * Update OrderStatusHistory
     */
    public OrderStatusHistory update(Long id, OrderStatusHistory entity) {
        log.info("Updating OrderStatusHistory with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete OrderStatusHistory
     */
    public void delete(Long id) {
        log.info("Deleting OrderStatusHistory with ID: {}", id);
        repository.deleteById(id);
    }
}
