package com.iwos.service;

import com.iwos.entity.OrderItem;
import com.iwos.repository.OrderItemRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * OrderItem Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles OrderItem business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class OrderItemService {

    private final OrderItemRepository repository;

    /**
     * Get all OrderItems
     */
    @Transactional(readOnly = true)
    public List<OrderItem> getAll() {
        log.info("Fetching all OrderItems");
        return repository.findAll();
    }

    /**
     * Get OrderItem by ID
     */
    @Transactional(readOnly = true)
    public Optional<OrderItem> getById(Long id) {
        log.info("Fetching OrderItem with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create OrderItem
     */
    public OrderItem create(OrderItem entity) {
        log.info("Creating new OrderItem");
        return repository.save(entity);
    }

    /**
     * Update OrderItem
     */
    public OrderItem update(Long id, OrderItem entity) {
        log.info("Updating OrderItem with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete OrderItem
     */
    public void delete(Long id) {
        log.info("Deleting OrderItem with ID: {}", id);
        repository.deleteById(id);
    }
}
