package com.iwos.repository;

import com.iwos.entity.Inventory;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Inventory Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface InventoryRepository extends JpaRepository<Inventory, Long> {

    // Add custom query methods here
    // Example: Optional<Inventory> findByName(String name);
}
