package com.iwos.repository;

import com.iwos.entity.InventoryTransaction;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * InventoryTransaction Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface InventoryTransactionRepository extends JpaRepository<InventoryTransaction, Long> {

    // Add custom query methods here
    // Example: Optional<InventoryTransaction> findByName(String name);
}
