package com.iwos.repository;

import com.iwos.entity.InventoryTransaction;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

/**
 * InventoryTransaction Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface InventoryTransactionRepository extends JpaRepository<InventoryTransaction, Long> {

    /**
     * Find all transactions for an inventory item
     */
    List<InventoryTransaction> findByInventoryId(Long inventoryId);

    /**
     * Find transactions by reference (e.g., order ID)
     */
    List<InventoryTransaction> findByReferenceTypeAndReferenceId(String referenceType, Long referenceId);

    /**
     * Find transactions by type
     */
    List<InventoryTransaction> findByTransactionType(String transactionType);

    /**
     * Find transactions for an inventory item ordered by ID descending
     */
    List<InventoryTransaction> findByInventoryIdOrderByIdDesc(Long inventoryId);
}
