package com.iwos.repository;

import com.iwos.entity.SKU;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * SKU Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface SKURepository extends JpaRepository<SKU, Long> {

    /**
     * Find SKU by SKU code
     */
    Optional<SKU> findBySkuCode(String skuCode);

    /**
     * Find active SKUs
     */
    List<SKU> findByIsActiveTrue();

    /**
     * Find SKUs by category
     */
    List<SKU> findByCategory(String category);

    /**
     * Check if SKU code already exists
     */
    boolean existsBySkuCode(String skuCode);
}
