package com.iwos.repository;

import com.iwos.entity.SKU;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * SKU Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface SKURepository extends JpaRepository<SKU, Long> {

    // Add custom query methods here
    // Example: Optional<SKU> findByName(String name);
}
