name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER)"
template: |
  ## Changes

  $CHANGES

categories:
  - title: "Architecture"
    labels:
      - architecture
  - title: "Infrastructure"
    labels:
      - infra
      - platform
  - title: "Documentation"
    labels:
      - documentation
  - title: "Services"
    labels:
      - commerce
      - fulfillment
      - network
      - intelligence

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - enhancement
      - feature
  patch:
    labels:
      - bug
      - documentation
      - infra
  default: patch
