package com.iwos.controller;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * AuthController
 * Auto-generated by IWOS Code Generator
 */
@RestController
@RequestMapping("/api/v1")
@RequiredArgsConstructor
@Slf4j
@CrossOrigin(origins = "${security.allowed-origins}")
public class AuthController {

    // Inject services here

    /**
     * Register new user
     */
    @POSTMapping("/auth/register")
    public ResponseEntity<?> register() {
        log.info("Register new user");
        // TODO: Implement register
        return ResponseEntity.ok("TODO: Implement register");
    }

    /**
     * User login
     */
    @POSTMapping("/auth/login")
    public ResponseEntity<?> login() {
        log.info("User login");
        // TODO: Implement login
        return ResponseEntity.ok("TODO: Implement login");
    }

    /**
     * Refresh JWT token
     */
    @POSTMapping("/auth/refresh")
    public ResponseEntity<?> refreshToken() {
        log.info("Refresh JWT token");
        // TODO: Implement refreshToken
        return ResponseEntity.ok("TODO: Implement refreshToken");
    }

    /**
     * Get current user
     */
    @GETMapping("/auth/me")
    public ResponseEntity<?> getCurrentUser() {
        log.info("Get current user");
        // TODO: Implement getCurrentUser
        return ResponseEntity.ok("TODO: Implement getCurrentUser");
    }

    /**
     * Logout user
     */
    @POSTMapping("/auth/logout")
    public ResponseEntity<?> logout() {
        log.info("Logout user");
        // TODO: Implement logout
        return ResponseEntity.ok("TODO: Implement logout");
    }

}
