package com.iwos.repository;

import com.iwos.entity.OrderStatusHistory;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * OrderStatusHistory Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface OrderStatusHistoryRepository extends JpaRepository<OrderStatusHistory, Long> {

    // Add custom query methods here
    // Example: Optional<OrderStatusHistory> findByName(String name);
}
