package com.iwos.repository;

import com.iwos.entity.Order;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Order Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface OrderRepository extends JpaRepository<Order, Long> {

    // Add custom query methods here
    // Example: Optional<Order> findByName(String name);
}
