package com.iwos.repository;

import com.iwos.entity.OrderItem;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * OrderItem Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface OrderItemRepository extends JpaRepository<OrderItem, Long> {

    // Add custom query methods here
    // Example: Optional<OrderItem> findByName(String name);
}
