apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iwos-dev
spec:
  source:
    repoURL: REPLACE_ME
    path: deploy/envs/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: iwos-platform
