apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iwos-root
spec:
  source:
    path: deploy/envs/prod
    repoURL: REPLACE_ME
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
