package com.iwos.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * InventoryTransaction Entity
 * Auto-generated by IWOS Code Generator
 */
@Entity
@Table(name = "inventory_transactions")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class InventoryTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // TODO: Add @ManyToOne relationship
    private Long inventoryId;

    private String transactionType;

    private Integer quantity;

    private Integer quantityBefore;

    private Integer quantityAfter;

    private String referenceType;

    private Long referenceId;

    @Column(columnDefinition = "TEXT")
    private String notes;

}
