package com.iwos.service;

import com.iwos.entity.Warehouse;
import com.iwos.repository.WarehouseRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * Warehouse Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles Warehouse business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class WarehouseService {

    private final WarehouseRepository repository;

    /**
     * Get all Warehouses
     */
    @Transactional(readOnly = true)
    public List<Warehouse> getAll() {
        log.info("Fetching all Warehouses");
        return repository.findAll();
    }

    /**
     * Get Warehouse by ID
     */
    @Transactional(readOnly = true)
    public Optional<Warehouse> getById(Long id) {
        log.info("Fetching Warehouse with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create Warehouse
     */
    public Warehouse create(Warehouse entity) {
        log.info("Creating new Warehouse");
        return repository.save(entity);
    }

    /**
     * Update Warehouse
     */
    public Warehouse update(Long id, Warehouse entity) {
        log.info("Updating Warehouse with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Warehouse
     */
    public void delete(Long id) {
        log.info("Deleting Warehouse with ID: {}", id);
        repository.deleteById(id);
    }
}
