package com.iwos.service;

import com.iwos.entity.Zone;
import com.iwos.repository.ZoneRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * Zone Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles Zone business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class ZoneService {

    private final ZoneRepository repository;

    /**
     * Get all Zones
     */
    @Transactional(readOnly = true)
    public List<Zone> getAll() {
        log.info("Fetching all Zones");
        return repository.findAll();
    }

    /**
     * Get Zone by ID
     */
    @Transactional(readOnly = true)
    public Optional<Zone> getById(Long id) {
        log.info("Fetching Zone with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create Zone
     */
    public Zone create(Zone entity) {
        log.info("Creating new Zone");
        return repository.save(entity);
    }

    /**
     * Update Zone
     */
    public Zone update(Long id, Zone entity) {
        log.info("Updating Zone with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Zone
     */
    public void delete(Long id) {
        log.info("Deleting Zone with ID: {}", id);
        repository.deleteById(id);
    }
}
