package com.iwos.repository;

import com.iwos.entity.Warehouse;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Warehouse Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface WarehouseRepository extends JpaRepository<Warehouse, Long> {

    // Add custom query methods here
    // Example: Optional<Warehouse> findByName(String name);
}
