package com.iwos.repository;

import com.iwos.entity.Zone;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Zone Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface ZoneRepository extends JpaRepository<Zone, Long> {

    // Add custom query methods here
    // Example: Optional<Zone> findByName(String name);
}
