package com.iwos.service;

import com.iwos.entity.RefreshToken;
import com.iwos.repository.RefreshTokenRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * RefreshToken Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles RefreshToken business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class RefreshTokenService {

    private final RefreshTokenRepository repository;

    /**
     * Get all RefreshTokens
     */
    @Transactional(readOnly = true)
    public List<RefreshToken> getAll() {
        log.info("Fetching all RefreshTokens");
        return repository.findAll();
    }

    /**
     * Get RefreshToken by ID
     */
    @Transactional(readOnly = true)
    public Optional<RefreshToken> getById(Long id) {
        log.info("Fetching RefreshToken with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create RefreshToken
     */
    public RefreshToken create(RefreshToken entity) {
        log.info("Creating new RefreshToken");
        return repository.save(entity);
    }

    /**
     * Update RefreshToken
     */
    public RefreshToken update(Long id, RefreshToken entity) {
        log.info("Updating RefreshToken with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete RefreshToken
     */
    public void delete(Long id) {
        log.info("Deleting RefreshToken with ID: {}", id);
        repository.deleteById(id);
    }
}
