package com.iwos.service;

import com.iwos.entity.Role;
import com.iwos.repository.RoleRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * Role Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles Role business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class RoleService {

    private final RoleRepository repository;

    /**
     * Get all Roles
     */
    @Transactional(readOnly = true)
    public List<Role> getAll() {
        log.info("Fetching all Roles");
        return repository.findAll();
    }

    /**
     * Get Role by ID
     */
    @Transactional(readOnly = true)
    public Optional<Role> getById(Long id) {
        log.info("Fetching Role with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create Role
     */
    public Role create(Role entity) {
        log.info("Creating new Role");
        return repository.save(entity);
    }

    /**
     * Update Role
     */
    public Role update(Long id, Role entity) {
        log.info("Updating Role with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Role
     */
    public void delete(Long id) {
        log.info("Deleting Role with ID: {}", id);
        repository.deleteById(id);
    }
}
