package com.iwos.service;

import com.iwos.entity.User;
import com.iwos.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * User Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles User business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class UserService {

    private final UserRepository repository;

    /**
     * Get all Users
     */
    @Transactional(readOnly = true)
    public List<User> getAll() {
        log.info("Fetching all Users");
        return repository.findAll();
    }

    /**
     * Get User by ID
     */
    @Transactional(readOnly = true)
    public Optional<User> getById(Long id) {
        log.info("Fetching User with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create User
     */
    public User create(User entity) {
        log.info("Creating new User");
        return repository.save(entity);
    }

    /**
     * Update User
     */
    public User update(Long id, User entity) {
        log.info("Updating User with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete User
     */
    public void delete(Long id) {
        log.info("Deleting User with ID: {}", id);
        repository.deleteById(id);
    }
}
