package com.iwos.orderorchestrator.domain.workflow;

public enum OrderWorkflowStatus {
    INVENTORY_RESERVATION_IN_PROGRESS,
    INVENTORY_RESERVED,
    INVENTORY_RESERVATION_FAILED,
    PAYMENT_AUTHORIZATION_IN_PROGRESS,
    PAYMENT_AUTHORIZED,
    PAYMENT_AUTHORIZATION_FAILED
}
