package com.iwos.repository;

import com.iwos.entity.RefreshToken;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * RefreshToken Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface RefreshTokenRepository extends JpaRepository<RefreshToken, Long> {

    // Add custom query methods here
    // Example: Optional<RefreshToken> findByName(String name);
}
