package com.iwos.repository;

import com.iwos.entity.Role;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Role Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface RoleRepository extends JpaRepository<Role, Long> {

    // Add custom query methods here
    // Example: Optional<Role> findByName(String name);
}
