package com.iwos.repository;

import com.iwos.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * User Repository
 * Auto-generated by IWOS Code Generator
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    // Add custom query methods here
    // Example: Optional<User> findByName(String name);
}
