apiVersion: v1
kind: ConfigMap
metadata:
  name: iwos-config
  namespace: iwos
data:
  EUREKA_SERVER: http://iwos-discovery-server:8761/eureka/
  KAFKA_SERVERS: iwos-kafka:9092
  REDIS_HOST: iwos-redis
  DB_HOST: iwos-postgres
