package com.iwos.service;

import com.iwos.entity.InventoryTransaction;
import com.iwos.repository.InventoryTransactionRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * InventoryTransaction Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles InventoryTransaction business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class InventoryTransactionService {

    private final InventoryTransactionRepository repository;

    /**
     * Get all InventoryTransactions
     */
    @Transactional(readOnly = true)
    public List<InventoryTransaction> getAll() {
        log.info("Fetching all InventoryTransactions");
        return repository.findAll();
    }

    /**
     * Get InventoryTransaction by ID
     */
    @Transactional(readOnly = true)
    public Optional<InventoryTransaction> getById(Long id) {
        log.info("Fetching InventoryTransaction with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create InventoryTransaction
     */
    public InventoryTransaction create(InventoryTransaction entity) {
        log.info("Creating new InventoryTransaction");
        return repository.save(entity);
    }

    /**
     * Update InventoryTransaction
     */
    public InventoryTransaction update(Long id, InventoryTransaction entity) {
        log.info("Updating InventoryTransaction with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete InventoryTransaction
     */
    public void delete(Long id) {
        log.info("Deleting InventoryTransaction with ID: {}", id);
        repository.deleteById(id);
    }
}
