package com.iwos.service;

import com.iwos.entity.Inventory;
import com.iwos.repository.InventoryRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * Inventory Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles Inventory business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class InventoryService {

    private final InventoryRepository repository;

    /**
     * Get all Inventorys
     */
    @Transactional(readOnly = true)
    public List<Inventory> getAll() {
        log.info("Fetching all Inventorys");
        return repository.findAll();
    }

    /**
     * Get Inventory by ID
     */
    @Transactional(readOnly = true)
    public Optional<Inventory> getById(Long id) {
        log.info("Fetching Inventory with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create Inventory
     */
    public Inventory create(Inventory entity) {
        log.info("Creating new Inventory");
        return repository.save(entity);
    }

    /**
     * Update Inventory
     */
    public Inventory update(Long id, Inventory entity) {
        log.info("Updating Inventory with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Inventory
     */
    public void delete(Long id) {
        log.info("Deleting Inventory with ID: {}", id);
        repository.deleteById(id);
    }
}
