package com.iwos.service;

import com.iwos.entity.SKU;
import com.iwos.repository.SKURepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * SKU Service
 * Auto-generated by IWOS Code Generator
 *
 * SOLID Principles:
 * - Single Responsibility: Handles SKU business logic
 * - Dependency Inversion: Depends on repository abstraction
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class SKUService {

    private final SKURepository repository;

    /**
     * Get all SKUs
     */
    @Transactional(readOnly = true)
    public List<SKU> getAll() {
        log.info("Fetching all SKUs");
        return repository.findAll();
    }

    /**
     * Get SKU by ID
     */
    @Transactional(readOnly = true)
    public Optional<SKU> getById(Long id) {
        log.info("Fetching SKU with ID: {}", id);
        return repository.findById(id);
    }

    /**
     * Create SKU
     */
    public SKU create(SKU entity) {
        log.info("Creating new SKU");
        return repository.save(entity);
    }

    /**
     * Update SKU
     */
    public SKU update(Long id, SKU entity) {
        log.info("Updating SKU with ID: {}", id);
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete SKU
     */
    public void delete(Long id) {
        log.info("Deleting SKU with ID: {}", id);
        repository.deleteById(id);
    }
}
