package com.iwos.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Order Entity
 * Auto-generated by IWOS Code Generator
 */
@Entity
@Table(name = "orders")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true)
    private String orderNumber;

    private String customerName;

    private String customerEmail;

    @Column(columnDefinition = "TEXT")
    private String shippingAddress;

    // TODO: Add @ManyToOne relationship
    private Long warehouseId;

    private String status;

    private Integer totalItems;

    private BigDecimal totalAmount;

    // TODO: Add @ManyToOne relationship
    private Long assignedTo;

}
