spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:55432/iwos
    username: iwos
    password: iwos_secret

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

iwos:
  order-orchestrator:
    inventory-service-base-url: http://localhost:8082
    promise-service-base-url: http://localhost:8084
    payment-service-base-url: http://localhost:8085
    default-fulfillment-node-id: NODE-DELHI-01
    pending-fetch-limit: 25
