server:
  port: 8093
spring:
  application:
    name: iwos-pricing-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/iwos_pricing
    username: ${DB_USERNAME:iwos}
    password: ${DB_PASSWORD:iwos_secret}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
